title: Github X Project
author: sergiomeneses
email: sergioandresmeneses@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Test site for the pages feature.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
